version: '3.8'

services:
  mcp-server:
    build: ./mcp-server
    ports:
      - "8000:8000"
    env_file:
      - ./mcp-server/.env
    volumes:
      - ./mcp-server/temp:/app/temp  # For persistent file storage
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mcp-assistant:
    build: ./mcp-assistant
    ports:
      - "8501:8501"
    env_file:
      - ./mcp-assistant/.env
    environment:
      - LICA_MCP_URL=http://mcp-server:8000/mcp
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    depends_on:
      mcp-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: lica-mcp-network
